#!/bin/bash

status=$(cat /sys/class/power_supply/BAT0/status)
battery=$(cat /sys/class/power_supply/BAT0/capacity)

if [[ $status == "Charging" ]]; then
  notify-send "$battery" "Charging"
elif [[ $status == "Not charging" ]]; then
  notify-send "$battery" "Stable as fuck"
else
  notify-send "$battery" "Discharging"
fi
